import json
import csv
from pathlib import Path

def format_num(val, fmt="{:.3f}"):
    try:
        return fmt.format(float(val))
    except (ValueError, TypeError):
        return r"\textcolor{red}{[TBD]}"

def read_json(path):
    try:
        with open(path, 'r') as f:
            return json.load(f)
    except Exception:
        return {}

def build_macros():
    results_paper = Path('results/paper')
    results_audit = Path('results/audit')
    results_dir = Path('results')
    paper_dir = Path('paper')
    
    paper_dir.mkdir(parents=True, exist_ok=True)
    
    macros = []
    
    # Helper to add macro
    def add(name, val):
        if val is None or val == "" or val == r"\textcolor{red}{[TBD]}":
            macros.append(f"\\newcommand{{\\{name}}}{{\\textcolor{{red}}{{[TBD]}}}}")
        else:
            macros.append(f"\\newcommand{{\\{name}}}{{{val}}}")

    # 1. Honest Baselines from experiment_registry.csv
    cnn_gru_f1 = None
    xgb_f1 = None
    try:
        with open(results_dir / 'experiment_registry.csv', 'r') as f:
            reader = csv.DictReader(f)
            for row in reader:
                if row['experiment_id'] == 'F_strict_no_mqtt_binary_best_s42':
                    cnn_gru_f1 = format_num(row['macro_f1'])
                if row['experiment_id'] == 'N01_xgb_binary_strict_nomqtt':
                    xgb_f1 = format_num(row['macro_f1'])
    except Exception:
        pass
        
    add("CnnGruFone", cnn_gru_f1)
    add("XgbFone", xgb_f1)
    
    # 2. Ceiling numbers
    ceiling_data = read_json(results_audit / 'detection_ceiling.json')
    edge_ceiling = ceiling_data.get("Edge-IIoTset (strict, no MQTT)", {})
    
    ceiling_pct = edge_ceiling.get("lookup_detection_rate_on_seen")
    hidden_pct = edge_ceiling.get("attacks_with_mostly_normal_pattern")
    
    add("CeilingDetect", format_num(ceiling_pct * 100, "{:.1f}\\%") if ceiling_pct else None)
    add("HiddenPct", format_num(hidden_pct * 100, "{:.1f}\\%") if hidden_pct else None)
    
    # 3. Ferrag Replication (B1)
    ferrag = read_json(results_paper / 'ferrag_replication.json')
    replicated = ferrag.get('replicated', {}).get('accuracy')
    cleaned = ferrag.get('strict', {}).get('accuracy')
    
    add("FerragRepAcc", format_num(replicated * 100, "{:.2f}\\%") if replicated else None)
    add("FerragCleanAcc", format_num(cleaned * 100, "{:.2f}\\%") if cleaned else None)
    
    # 4. Fidelity (A9 / B2 / B5)
    fidelity = read_json(results_dir / 'shap_fidelity.json')
    fid_drop = fidelity.get('FID_drop_top5_shap', {}).get('macro_f1')
    
    add("FidTopFive", format_num(fid_drop) if fid_drop else None)
    
    # Write out
    out_path = paper_dir / 'numbers.tex'
    with open(out_path, 'w') as f:
        f.write("% Auto-generated by build_numbers.py. Do not edit manually.\n")
        f.write("\n".join(macros) + "\n")
        
    print(f"Generated {len(macros)} macros in {out_path}")

if __name__ == '__main__':
    build_macros()
